server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://localhost:3306/menu_auth?useUnicode=true&characterEncoding=utf8&useSSL=false

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.smile.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl